local Luau = {}
Luau.BytecodeTag = {
	CONSTANT_NIL = 0,
	CONSTANT_BOOLEAN = 1,
	CONSTANT_NUMBER = 2,
	CONSTANT_STRING = 3,
	CONSTANT_IMPORT = 4,
	CONSTANT_TABLE = 5,
	CONSTANT_CLOSURE = 6,
	CONSTANT_VECTOR = 7
}

return Luau